# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACM@WM
email: exec@wm.acm.org
description: > # this means to ignore newlines until "baseurl:"
    The William & Mary Chapter of the Association for Computing Machinery
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acmwm.github.io/" # the base hostname & protocol for your site

github_username:  ACMWM
slack: wmacm
facebook: ACMWM

include: [_pages]

# Build settings
markdown: kramdown

year: 2019-2020
officers:
    - job: Chair
      name: Meg Anderson
      pic: meg.jpg
      bio: >
          Meg is a senior studying Computer Science and Biology here at the college. When she's not hanging out with ACM, you can find her in the bowels of McGlothlin Street helping intro computer science students as a consultant, or at the German house trying not to forgot how to <em>Deutsch sprechen</em> after her summer internship in Germany. Makes a killer crème brûlée.

    - job: Vice Chair
      name: Alex Fantine
      pic: alex.png
      bio: >
          Alex is a junior planning on majoring in Computer Science and possibly minoring in theatre. Aside from planning weekly meetings, you can usually catch him acting in some production at W&M or trying to think of a cool idea for a coding project. He also really likes Transformers, and is looking for someone to geek out about the Lost Light with!

    - job: Secretary
      name: Wils McCreight
      pic: wils.png
      bio: >
          Wils is a senior with a double major in Computer Science and Data science. He loves dogs and music, and he drinks a moderate amount of coffee. He is also a big fan of computers! He spends his time developing IOS apps and occasionally baking some killer scones. As Secretary he coordinates with his fellow officers, the William & Mary Computer Science faculty and the national ACM organization to set records straight and to keep communication constant and smooth.

    - job: Treasurer
      name: Sophia Armitano
      pic:
      bio:

    - job: PR Chair
      name: AJ Marra
      pic: aj.jpg
      bio: >
          AJ is a senior majoring in Computer Science and minoring in English. Aside from all things computers and programming, AJ enjoys reading, writing, playing soccer, and swimming. She is also a sister of Alpha Chi Omega and subsists off of coffee and sugar.

    - job: Webmaster
      name: Jacob Adams
      pic:
      bio:

    - job: Cypher Chair
      name: Ben Ryan
      pic:
      bio:

    - job: TIP Chair
      name: Liz Weech
      pic: liz.png
      bio: >
          Liz is a senior studying Computer Science and Physics. She is the firmware lead for TribeSat, W&M's satellite project, and gets really excited about anything space related. Milk is her beverage of choice, and she reached her peak when she met Buzz Aldrin at a conference in 2014.

    - job: Hackathon Chair
      name: Adam An
      pic: adam.png
      bio:

    - job: Graduate Student Liason
      name: Richie Bonett
      pic: richie.jpg
      bio: >
          Richie is a MS/PhD student advised by <a href="http://www.cs.wm.edu/~denys/">Dr. Denys Poshyvanyk</a>. His primary research interests lie in Software Engineering, particularly in the development and evolution of mobile applications. You can read more about his work and technical interests on <a href="http://richardbonett.com/">his website</a>.

    - job: Faculty Advisor
      name: Jim Deverick
      pic: jim.jpg
      bio:
