# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACM@WM
email: exec@wm.acm.org
description: > # this means to ignore newlines until "baseurl:"
  The William & Mary Chapter of the Association for Computing Machinery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acm.cs.wm.edu/" # the base hostname & protocol for your site

github_username: ACMWM
slack: wmacm
facebook: ACMWM
instagram: acmwm

include: [_pages]
exclude: [LICENSE, post-receive, deploy.sh]

# Build settings
markdown: kramdown

year: 2021
officers:
  - job: Chair
    name: Mandy Michel
    pic: mandy.jpg
    bio: >
              Mandy is a junior intending to double major in Computer Science and Math. She likes exploring all sorts of CS concepts and is always open to learning something new. When not learning new things or refining her LaTeX templates, Mandy loves watching (and arguing about) Star Wars, playing the Witcher 3, and crocheting. She also has a propensity for fun facts. Here's one for you now: Frankenstein's monster is a vegetarian!

  - job: Vice Chair
    name: Kelley Wang
    pic: kelley.jpg
    bio: >
        Kelley Wang is a junior double majoring in CS and Art and Art History with a concentration in studio art. She has an interest in UI/UX design and is currently doing research for W&M’s DH Lab. While she is not coding, she enjoys gardening and playing games with friends. 


  - job: Secretary + Historian
    name: Joseph Lee
    pic: joseph.jpg
    bio: >
            Joseph is a sophomore with an intended double major in Computer Science and Applied Math. He loves to study artificial intelligence, machine learning, and software development. He also loves to play on his piano ane violin. Currently, even though it is outside of his technical skills, he is attempting to learn Rachmanioff's Prelude in G Minor on the piano.
            Generally, he is introverted, but when placed in the right environment, he can be quite lively. As seen on the profile pic on the left, he also loves to ponder and ask many deep, philosophical, and intriguing questions. Feel free to reach him at <a href="mailto:jslee08@wm.edu">jslee08@wm.edu</a> He is happy to help.
              

  - job: Treasurer
    name: TBD
    pic: kelley.jpg
    bio: >
      TBD
  
  - job: PR Chair
    name: Steven Jia
    pic: steven_jia.jpg
    bio: >
              Hi, I’m Steven Jia the PR Chair for the 2021 Fall semester. When I’m not coding, I like to play video games and going to the gym.

  - job: Webmaster
    name: Manav Kapoor
    pic: joseph.jpg
    bio: >
      Hello, world!

  - job: Cypher Chair
    name: Victor Tran
    pic: victor.jpg
    bio: >
              Victor is the lead organizer for the next two Cyphers, William & Mary’s annual hackathon. He is a junior double majoring in Computer Science & Linguistics with a focus on Web Development and Natural Language Processing. When Victor isn’t spamming tech companies for Cypher sponsorships or writing advertisements, he’s taking advantage of the stay-at-home situation by attending several online hackathons. He is also interested in cardistry and building model kits.
            

  - job: TIP Chair
    name: Ronan Donovan
    pic: ronan.png
    bio: >
              Ronan is a junior studying Computer Science and Data Science. He’s always prepared to talk through a tough programming question. If you need someone to LeetCode or HackerRank alongside you, send him an email at <a href="mailto:rcdonovan@email.wm.edu">rcdonovan@email.wm.edu</a>. He can also be found walking around campus with his dog, an English cream retriever.
            

  - job: Hackathon Chair
    name: Robert West
    pic: robert.png
    bio: >
              Robert is a junior studying Computer Science and Psychology. He's passionate about using technology to improve education and increase civic engagement. When he's not focused on his CS work, he's typically found hanging out outdoors, especially on the trails around Lake Matoaka.
              

  - job: Faculty Advisor
    name: Jim Deverick
    pic: jim.jpg
    bio:
