# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WMACM
email: exec@wm.acm.org
description: > # this means to ignore newlines until "baseurl:"
    The William & Mary Chapter of the Association for Computing Machinery

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  ACMWM

include: [_pages]

# Navigation Bar Contents
navigation:
    - name: Membership
      url: /membership

    - name: Officers
      url: /officers

    - name: TIP
      url: /tip

    - name: Hardware Lab
      url: /hwlab

    - name: ICPC
      url: /icpc

    - name: ACM-W
      url: /acm-w

    - name: Cypher
      url: http://cypher.cs.wm.edu/

# Build settings
markdown: kramdown

