# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACM@WM
email: exec@wm.acm.org
description: > # this means to ignore newlines until "baseurl:"
  The William & Mary Chapter of the Association for Computing Machinery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acm.cs.wm.edu/" # the base hostname & protocol for your site

github_username: ACMWM
slack: wmacm
facebook: ACMWM
instagram: acmwm

include: [_pages]
exclude: [LICENSE, post-receive, deploy.sh]

# Build settings
markdown: kramdown

year: 2023
officers:
  - job: Chair
    name: Mandy Michel
    pic: mandy.jpg
    bio: >
              Mandy is a senior double majoring in Computer Science and Linguistics. She likes exploring all sorts of CS concepts, but has particular interests in NLP and Cybersecurity. When not learning new things or refining her LaTeX templates, Mandy loves watching (and arguing about) Star Wars, playing the Legend of Zelda games, and embroidery. She also has a propensity for fun facts. Here's one for you now: Frankenstein's monster is a vegetarian!

  - job: Vice Chair
    name: Jackson Kubin
    pic: jackson.jpg
    bio: >
        Jackson is a junior majoring in Computer Science with a minor in Linguistics. When he’s not coding, he’s probably thinking about how whatever he’s actually doing would be faster and easier if he coded it instead (not counting the time taken to actually code it, of course). He’s in two singing groups on campus, the Wrens and the Bots. He also loves to bake, and is always looking to try a new recipe.

  - job: Secretary + Historian
    name: Manav Kapoor
    pic: manav.jpg
    bio: >
            Hey guys, I'm happy to serve as your secretary and historian for 2023 school year. I am currently a junior studying computer science. I love music and a bunch of other things. If you have any questions about the mailing list, or just in general, feel free to email me at mkapoor@wm.edu 
              
  - job: Treasurer
    name: Ben Li
    pic: benLi.jpg
    bio: >
              Hello! My name is Ben; I'm a junior currently majoring in Computer Science, and I'm your treasurer for the 2023 school year. I've always had a strong interest in technology since I was a child, so I'm constantly trying to learn about random new tech, like smartphones or other devices. Outside of tech, my other pastimes include video games, editing videos, and writing scripts I will never record.

  - job: PR Chair
    name: Nadine Maysaud
    pic: nadine2.jpg
    bio: >
              Nadine is a senior, and runs our instagram page @ACMWM !

  - job: Webmaster
    name: Kelley Wang
    pic: kelley.jpg
    bio: >
              Kelley Wang is a senior double majoring in CS and Art and Art History with a concentration in studio art. She has an interest in UI/UX design and enjoys gardening.

  - job: Cypher Chair
    name: 
    pic: tbapic.jpg
    bio: 
            
  - job: TIP Chair
    name:
    pic: tbapic.jpg
    bio: 
            
  - job: Hackathon Chair
    name: Sam Murad
    pic: tbapic.jpg
    bio:
              
  - job: Faculty Advisor
    name: Jim Deverick
    pic: jim.jpg
    bio:
