# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACM@WM
email: exec@wm.acm.org
description: > # this means to ignore newlines until "baseurl:"
  The William & Mary Chapter of the Association for Computing Machinery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acm.cs.wm.edu/" # the base hostname & protocol for your site

github_username: ACMWM
slack: wmacm
facebook: ACMWM
instagram: acmwm

include: [_pages]
exclude: [LICENSE, post-receive, deploy.sh]

# Build settings
markdown: kramdown

year: 2020-2021
officers:
  - job: Chair
    name: Pablo Solano
    pic: pablo.jpg
    bio: >
              Pablo is a junior Computer Science major and Data Science minor. Pablo fell in love with ACM his last two years at the College, and he's excited to be serving his second term as an ACM@WM executive. His CS interests include video game development and cyber security. 
              Apart from his involvement in ACM, Pablo is the Fellow for technology at the Entrepreneurship Center, is developing a game for the Global Fund to End Modern Slavery, and hopes to sing at Hickory Neck Episcopal Church once live mass resumes. 
              During his free time, Pablo likes to spend time with his friends, work on his own coding projects, and play video games. If you have any questions about ACM (or anything else), you can reach him at <a href="mailto:pasolano@email.wm.edu">pasolano@email.wm.edu</a>.

  - job: Vice Chair
    name: Kerry Wang
    pic: kerry.jpg
    bio: >


  - job: Secretary
    name: Mandy Michel
    pic: mandy.jpg
    bio: >
              

  - job: Treasurer
    name: Gabriella Shelton
    pic: gabriella.jpg
    bio: >
              Gabriella is our treasurer.  She is currently a freshman and planning on majoring in computer science.
  
  - job: PR Chair
    name: Steven Jia
    pic:
    bio: >
              

  - job: Webmaster
    name: Joseph Lee
    pic: joseph.jpg
    bio: >
            Joseph is a freshman with an intended double major in Computer Science and Applied Math. He loves to study artificial intelligence, machine learning, and software development. He also loves to play on his piano ane violin. Currently, even though it is outside of his technical skills, he is attempting to learn Rachmanioff's Prelude in G Minor on the piano.
            Generally, he is introverted, but when placed in the right environment, he can be quite lively. As seen on the profile pic on the left, he also loves to ponder and ask many deep, philosophical, and intriguing questions. Feel free to reach him at <a href="mailto:jslee08@email.wm.edu">jslee08@email.wm.edu</a> He is happy to help.

  - job: Cypher Chair
    name: Victor Tran
    pic: victor.jpg
    bio: >
              Victor is the lead organizer for the next two Cyphers, William & Mary’s annual hackathon. He is a Sophomore double majoring in Computer Science & Linguistics with a focus on Web Development and Natural Language Processing. When Victor isn’t spamming tech companies for Cypher sponsorships or writing advertisements, he’s taking advantage of the stay-at-home situation by attending several online hackathons. He is also interested in cardistry and building model kits.
            

  - job: TIP Chair
    name: Ronan Donovan
    pic: 
    bio: >
            

  - job: Hackathon Chair
    name: Robert West
    pic: 
    bio: >
              

  - job: Faculty Advisor
    name: Jim Deverick
    pic: jim.jpg
    bio:
