# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACM@WM
email: exec@wm.acm.org
description: > # this means to ignore newlines until "baseurl:"
    The William & Mary Chapter of the Association for Computing Machinery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acm.cs.wm.edu/" # the base hostname & protocol for your site

github_username:  ACMWM
slack: wmacm
facebook: ACMWM
instagram: acmwm

include: [_pages]
exclude: [LICENSE, post-receive, deploy.sh]

# Build settings
markdown: kramdown

year: 2020-2021
officers:
    - job: Chair
      name: Alex Fantine
      pic: alex.png 
      bio: >
          alex desc

    - job: Vice Chair
      name: Jacob Adams
      pic: 
      bio: >
          jacob desc

    - job: Secretary
      name: Emily Wydra
      pic: 
      bio: >
          emily desc

    - job: Treasurer
      name: Sophia Armitano
      pic: 
      bio: >
          Sophia is a senior pursuing a self-designated major that intersects Computer Science, Data Science, GIS, and Native Studies. Her first language was Spanish, but is afraid of losing it while in Virginia, She loves baking, going to the farmers market, and spending time outdoors. She is also a proud Hermana of Hermandad de Sigma Iota Alpha, Incorporada, and is serving as the President this year.

    - job: PR Chair
      name: Jade Chen
      pic: 
      bio: >
          jade desc

    - job: Webmaster
      name: Kerry Wang
      pic:
      bio: >
          kerry desc

    - job: Cypher Chair
      name: Ben Ryan
      pic:
      bio:

    - job: TIP Chair
      name: Pablo Solano
      pic: 
      bio: >
          pablo desc

    - job: Hackathon Chair
      name: Christine Wang
      pic: 
      bio: >
          christine desc

    - job: Graduate Student Liason
      name: Richie Bonett
      pic: richie.jpg
      bio: >
          Richie is a MS/PhD student advised by <a href="http://www.cs.wm.edu/~denys/">Dr. Denys Poshyvanyk</a>. His primary research interests lie in Software Engineering, particularly in the development and evolution of mobile applications. You can read more about his work and technical interests on <a href="http://richardbonett.com/">his website</a>.

    - job: Faculty Advisor
      name: Jim Deverick
      pic: jim.jpg
      bio:
